apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab
  namespace: postgres
spec:
  storageClassName: nfs-common
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128Mi