apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: cicd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: processing
  project: default
  source:
    repoURL: 'https://googlecloudplatform.github.io/spark-on-k8s-operator'
    targetRevision: 1.1.27
    helm:
      values: |-
        image:
          tag: "v1beta2-1.3.8-3.1.1"
    chart: spark-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true