---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-user-openmetadata
  annotations:
    replicator.v1.mittwald.de/replicate-to: "openmetadata"
type: Opaque
data:
  password: "bWV0YXN0b3JlX2Ri"
