apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

resources:
  - kafka.yaml
  - kafka-bridge.yaml
  - kafka-topics.yaml
  - kafka-users.yaml
  - namespace.yaml
