apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jfrog-ingress-lab
  namespace: jfrog
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: lab.jfrog.worldl.xpt
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jfrog-artifactory-jcr-artifactory-nginx
                port:
                  number: 80
