global:
  datahub:
    #version: v0.12.1
    systemUpdate:
      ## The following options control settings for datahub-upgrade job which will
      ## managed ES indices and other update related work
      enabled: true

  sql:
    datasource:
      host: "postgres-postgresql.postgres.svc.cluster2.xpt:5432"
      hostForpostgresqlClient: "postgres-postgresql.postgres.svc.cluster2.xpt"
      port: "5432"
      url: "jdbc:postgresql://postgres-postgresql.postgres.svc.cluster2.xpt:5432/datahub"
      driver: "org.postgresql.Driver"
      username: "datahub"
      # kubectl get secret --namespace postgres postgres-user-datahub -o yaml
      # kubectl get secret --namespace datahub postgres-user-datahub -o yaml
      password:
        secretRef: postgres-user-datahub
        secretKey: password


datahub-ingestion-cron:
  enabled: false

elasticsearchSetupJob:
  enabled: true

mysqlSetupJob:
  enabled: false

postgresqlSetupJob:
  enabled: true

datahub-frontend:
  enabled: true
  resources:
    limits:
      memory: 1400Mi
    requests:
      cpu: 100m
      memory: 512Mi
  # Set up ingress to expose react front-end

  ingress:
    enabled: true
    # https://datahubproject.io/docs/deploy/aws/ search ingress
    hosts:
      - host: datahub.worldlb.xpt
        redirectPaths:
          - path: /*
            name: ssl-redirect
            port: "9002"
        paths:
          - /*

  defaultUserCredentials:
    manualValues: |
       datahub:manualPassword
       initialViewer:manualPassword