[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
O = system:nodes
CN = system:node:*.amazonaws.com

[v3_req]
subjectAltName = @alt_names

[alt_names]
DNS.1 = zeppelin.worldl.xpt
DNS.2 = *.amazonaws.com
