kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lab-claim
  namespace: zeppelin
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi

