apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-configmap
  namespace: kafka
data:
  config.yml: |-
    kafka:
      clusters:
        - name: main
          bootstrapServers: 10.111.38.197:9092
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false
