apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-user-bridge
  labels:
    strimzi.io/cluster: main
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
        operation: All
      - resource:
          type: group
          name: '*'
        operation: All
      - resource:
          type: cluster
          name: '*'
        operation: All