apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive
  labels:
    app.kubernetes.io/name: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hive-metastore
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: registry.minikube/hive-metastore-base-3.2:master
          #imagePullPolicy: Always
          env:
            - name: HIVE_SITE_CONF_metastore_warehouse_dir
              value: "s3a://spark/warehouse/"
            - name: HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName
              value: "org.postgresql.Driver"
            - name: HIVE_SITE_CONF_javax_jdo_option_ConnectionURL
              value: "jdbc:postgresql://postgres-postgresql.postgres.svc.cluster2.xpt:5432/metastore_db"
            - name: HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName
              value: "metastore_db"
            - name: HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword
              value: "metastore_db"
            - name: HIVE_SITE_CONF_fs_s3a_access_key
              value: "minio"
            - name: HIVE_SITE_CONF_fs_s3a_secret_key
              value: "awesomes3"
            - name: HIVE_SITE_CONF_fs_s3a_endpoint
              value: "https://minio.minio-tenant-1.svc.cluster2.xpt"
            - name: HIVE_SITE_CONF_fs_s3a_path_style_access
              value: "true"
          volumeMounts:
            - name: ca-pemstore
              mountPath: /usr/local/share/ca-certificates/
              readOnly: true
          ports:
            - name: metastore
              containerPort: 9083
      volumes:
        - name: ca-pemstore
          configMap:
            name: ca-pemstore
---
kind: Service
apiVersion: v1
metadata:
  name: hive-metastore
  namespace: hive
spec:
  ports:
    - name: hive-metastore
      port: 9083
  selector:
    app.kubernetes.io/name: hive-metastore
