apiVersion: v1
kind: ConfigMap
metadata:
  name: tunnel-server-conf
data:
  start.sh: |
      export AUTOSSH_LOGFILE="$HOME/autossh.log"
      export AUTOSSH_LOGLEVEL=7
      export AUTOSSH_DEBUG
     
      autossh -f -M 0 \
        -o "ServerAliveInterval 30" \
        -o "ServerAliveCountMax 3" \
        -N \
        -R 1080:127.0.0.1:1080 \
        -R 8888:127.0.0.1:8888 \
        -R 2222:127.0.0.1:22 \
        -R 8080:ingress.worldl.xpt:80 \
        -R 8443:ingress.worldl.xpt:443 \
        -p 22 \
        -i /tmp/ssh/id_rsa \
        -o "StrictHostKeyChecking=no" \
        mac@macos.worldl.xpt \
    
       tail -f "$HOME/autossh.log"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel-server
  labels:
    app.kubernetes.io/name: tunnel-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tunnel-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tunnel-server
    spec:
      volumes:
        - name: tunnel-conf
          configMap:
            name: tunnel-server-conf
            items:
              - key: start.sh
                path: start.sh
        - name: ssh
          secret:
            secretName: ssh
            optional: false
            defaultMode: 0700
      containers:
        - name: tunnel-server-gateway
          image: jfrog.worldl.xpt/lab/command
          imagePullPolicy: Never
          volumeMounts:
            - name: tunnel-conf
              readOnly: true
              mountPath: /tmp/conf
            - name: ssh
              readOnly: true
              mountPath: "/tmp/ssh"
