kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: metabase-db
  namespace: metabase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard-consumer